#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-bootstrap
Version  : 2019.6
Release  : 45
URL      : https://cran.r-project.org/src/contrib/bootstrap_2019.6.tar.gz
Source0  : https://cran.r-project.org/src/contrib/bootstrap_2019.6.tar.gz
Summary  : Functions for the Book "An Introduction to the Bootstrap"
Group    : Development/Tools
License  : BSD-3-Clause
Requires: R-bootstrap-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
for the book "An Introduction to the Bootstrap" by B. Efron and
        R. Tibshirani, 1993, Chapman and Hall. This package is
        primarily provided for projects already based on it, and for
        support of the book. New projects should preferentially use the
        recommended package "boot".

%package lib
Summary: lib components for the R-bootstrap package.
Group: Libraries

%description lib
lib components for the R-bootstrap package.


%prep
%setup -q -n bootstrap
pushd ..
cp -a bootstrap buildavx2
popd
pushd ..
cp -a bootstrap buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737136023

%install
export SOURCE_DATE_EPOCH=1737136023
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/bootstrap/DESCRIPTION
/usr/lib64/R/library/bootstrap/INDEX
/usr/lib64/R/library/bootstrap/LICENSE
/usr/lib64/R/library/bootstrap/Meta/Rd.rds
/usr/lib64/R/library/bootstrap/Meta/data.rds
/usr/lib64/R/library/bootstrap/Meta/features.rds
/usr/lib64/R/library/bootstrap/Meta/hsearch.rds
/usr/lib64/R/library/bootstrap/Meta/links.rds
/usr/lib64/R/library/bootstrap/Meta/nsInfo.rds
/usr/lib64/R/library/bootstrap/Meta/package.rds
/usr/lib64/R/library/bootstrap/NAMESPACE
/usr/lib64/R/library/bootstrap/NEWS
/usr/lib64/R/library/bootstrap/R/bootstrap
/usr/lib64/R/library/bootstrap/R/bootstrap.rdb
/usr/lib64/R/library/bootstrap/R/bootstrap.rdx
/usr/lib64/R/library/bootstrap/data/Rdata.rdb
/usr/lib64/R/library/bootstrap/data/Rdata.rds
/usr/lib64/R/library/bootstrap/data/Rdata.rdx
/usr/lib64/R/library/bootstrap/data/datalist
/usr/lib64/R/library/bootstrap/help/AnIndex
/usr/lib64/R/library/bootstrap/help/aliases.rds
/usr/lib64/R/library/bootstrap/help/bootstrap.rdb
/usr/lib64/R/library/bootstrap/help/bootstrap.rdx
/usr/lib64/R/library/bootstrap/help/paths.rds
/usr/lib64/R/library/bootstrap/html/00Index.html
/usr/lib64/R/library/bootstrap/html/R.css
/usr/lib64/R/library/bootstrap/tests/regressionTests.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/bootstrap/libs/bootstrap.so
/V4/usr/lib64/R/library/bootstrap/libs/bootstrap.so
/usr/lib64/R/library/bootstrap/libs/bootstrap.so
